# Generated by Django 5.0.1 on 2024-01-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenEnvio', models.CharField(max_length=60)),
                ('fechaGeneracion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(max_length=50)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='almacen', to='aplicacion.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Almacenes', to='aplicacion.almacen')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Inventarios', to='aplicacion.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operador', models.CharField(max_length=30)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personales_operador', to='aplicacion.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jefe', models.CharField(max_length=30)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personales_jefe', to='aplicacion.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gestor', models.CharField(max_length=30)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personales_gestor', to='aplicacion.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('categoria', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('fechaCaducidad', models.DateField()),
                ('fechaEntrada', models.DateField()),
                ('novedad', models.CharField(max_length=50)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='aplicacion.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicamento', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_insu_medi', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_medicos', to='aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DipositivoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disp_medi', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_medicos', to='aplicacion.producto')),
            ],
        ),
    ]
