# Generated by Django 5.0.1 on 2024-01-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_producto_fechacaducidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_inventario', to='aplicacion.inventario'),
        ),
    ]
